# This is a Docker Compose file for a Markdown blog application.
services:
  # PostgreSQL service
  db:
    image: postgres
    container_name: markdown_blog_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - markdown_blog_network
    env_file:
      - .env

  # API service
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    # image: api/latest
    container_name: markdown_blog_api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST_ADDRESS: ${HOST_ADDRESS}
      STATIC_PATH: ${STATIC_PATH}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - markdown_blog_network
    env_file:
      - .env

  # Web Client (Python/Flask)
  web_client:
    build:
      context: .
      dockerfile: web_client/Dockerfile
    # image: web_client/latest
    container_name: markdown_blog_web_client
    environment:
      - API_URL=http://markdown_blog_api:8080
    ports:
      - "5000:5000"
    depends_on:
      - api
    networks:
      - markdown_blog_network
    env_file:
      - .env

  # Useless Client (Python/Flask)
  useless_client:
    build:
      context: .
      dockerfile: useless_client/Dockerfile
    # image: useless_client/latest
    container_name: markdown_blog_useless_client
    environment:
      - API_URL=http://markdown_blog_api:8080
    ports:
      - "5050:5050"
    depends_on:
      - api
    networks:
      - markdown_blog_network
    env_file:
      - .env


networks:
  markdown_blog_network:
    driver: bridge