// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID         int32            `json:"id"`
	Hash       string           `json:"hash"`
	UploadedAt pgtype.Timestamp `json:"uploaded_at"`
}

type Note struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Path      string           `json:"path"`
	Content   string           `json:"content"`
	Hash      string           `json:"hash"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type NotesImage struct {
	NoteID  int32 `json:"note_id"`
	ImageID int32 `json:"image_id"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	ApiToken  string           `json:"api_token"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
