name: Build and Push to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build api Docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/mdblog_api:latest -f api/Dockerfile .

      - name: Build useless_client Docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/mdblog_useless_client:latest -f useless_client/Dockerfile .
      
      - name: Push api Docker image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/mdblog_api:latest
      
      - name: Push useless_client Docker image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/mdblog_useless_client:latest